// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/1340691923/ElasticView/pkg/api"
	"github.com/1340691923/ElasticView/pkg/infrastructure/access_control"
	"github.com/1340691923/ElasticView/pkg/infrastructure/config"
	"github.com/1340691923/ElasticView/pkg/infrastructure/dao"
	"github.com/1340691923/ElasticView/pkg/infrastructure/eve_api"
	"github.com/1340691923/ElasticView/pkg/infrastructure/jwt_svr"
	"github.com/1340691923/ElasticView/pkg/infrastructure/logger"
	"github.com/1340691923/ElasticView/pkg/infrastructure/middleware"
	"github.com/1340691923/ElasticView/pkg/infrastructure/orm"
	"github.com/1340691923/ElasticView/pkg/infrastructure/orm/migrator"
	"github.com/1340691923/ElasticView/pkg/infrastructure/plugin_rpc"
	"github.com/1340691923/ElasticView/pkg/infrastructure/plugins/manager"
	"github.com/1340691923/ElasticView/pkg/infrastructure/plugins/manager/process"
	"github.com/1340691923/ElasticView/pkg/infrastructure/pluginstore"
	"github.com/1340691923/ElasticView/pkg/infrastructure/request"
	"github.com/1340691923/ElasticView/pkg/infrastructure/response"
	"github.com/1340691923/ElasticView/pkg/infrastructure/web_engine"
	"github.com/1340691923/ElasticView/pkg/registry"
	"github.com/1340691923/ElasticView/pkg/server/backgroundsvcs"
	"github.com/1340691923/ElasticView/pkg/services/big_mode_service"
	"github.com/1340691923/ElasticView/pkg/services/cache_service"
	"github.com/1340691923/ElasticView/pkg/services/es"
	"github.com/1340691923/ElasticView/pkg/services/es_link_service"
	"github.com/1340691923/ElasticView/pkg/services/es_service"
	"github.com/1340691923/ElasticView/pkg/services/eve_service"
	"github.com/1340691923/ElasticView/pkg/services/gm_operater_log"
	"github.com/1340691923/ElasticView/pkg/services/gm_role"
	"github.com/1340691923/ElasticView/pkg/services/gm_user"
	"github.com/1340691923/ElasticView/pkg/services/live_svr"
	"github.com/1340691923/ElasticView/pkg/services/oauth"
	"github.com/1340691923/ElasticView/pkg/services/plugin_install_service"
	"github.com/1340691923/ElasticView/pkg/services/plugin_service"
	"github.com/1340691923/ElasticView/pkg/services/updatechecker"
	"github.com/1340691923/ElasticView/pkg/services/webview"
	"github.com/1340691923/ElasticView/pkg/web"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Initialize(args *config.CommandLineArgs) (*Server, error) {
	configConfig, err := config.InitConfig(args)
	if err != nil {
		return nil, err
	}
	zapLogger, err := logger.InitLog(configConfig)
	if err != nil {
		return nil, err
	}
	gorm, err := orm.NewGorm(configConfig, zapLogger)
	if err != nil {
		return nil, err
	}
	rbac, err := access_control.NewRbac(configConfig, zapLogger, gorm)
	if err != nil {
		return nil, err
	}
	migratorMigrator := migrator.NewMigrator(gorm, configConfig, zapLogger, rbac)
	webEngine := web_engine.NewWebEngine()
	jwt := jwt_svr.NewJwt(configConfig, zapLogger, gorm)
	responseResponse := response.NewResponse(zapLogger)
	gmUserDao := dao.NewGmUserDao(gorm)
	gmRoleDao := dao.NewGmRoleDao(gorm)
	pluginManager := manager.NewPluginManager()
	workWechat := oauth.NewWorkWechat(configConfig)
	oAuthServiceRegistry := oauth.ProvideOAuthServiceRegistry(workWechat)
	gmUserService := gm_user.NewGmUserService(zapLogger, gmUserDao, gmRoleDao, jwt, pluginManager, configConfig, gorm, oAuthServiceRegistry)
	gmOperaterLogService := gm_operater_log.NewGmOperaterLogService(zapLogger, gorm)
	middleWareService := middleware.NewMiddleWareService(configConfig, gorm, zapLogger, jwt, responseResponse, gmUserService, rbac, webEngine, pluginManager, gmOperaterLogService)
	requestRequest := request.NewRequest()
	baseController := api.NewBaseController(requestRequest, responseResponse)
	gmOperaterController := api.NewGmOperaterController(baseController, zapLogger, configConfig, gmOperaterLogService)
	gmRoleService := gm_role.NewGmRoleService(zapLogger, gmRoleDao)
	esCache := cache_service.NewEsCache()
	esLinkV2Dao := dao.NewEsLinkV2Dao(gorm)
	esClientService := es.NewEsClientService(configConfig, esCache, esLinkV2Dao, gmUserDao, gorm)
	eslinkCfgV2Dao := dao.NewEslinkCfgV2Dao(gorm)
	gmRoleEslinkCfgV2Dao := dao.NewGmRoleEslinkCfgV2Dao(gorm)
	eslinkRoleCfgReletionDao := dao.NewEslinkRoleCfgReletion(gorm)
	esLinkService := es_link_service.NewEsLinkService(gorm, zapLogger, esClientService, eslinkCfgV2Dao, gmRoleEslinkCfgV2Dao, eslinkRoleCfgReletionDao, gmUserDao, esLinkV2Dao)
	managerRoleController := api.NewManagerRoleController(baseController, zapLogger, configConfig, jwt, gmRoleService, gmUserService, rbac, gorm, esLinkService)
	esLinkController := api.NewEsLinkController(baseController, zapLogger, esClientService, gorm, esLinkService, jwt, esCache)
	evEApi := eve_api.NewEvApi(configConfig, zapLogger)
	evBackDao := dao.NewEvBackDao(zapLogger, evEApi)
	evUpdate, err := updatechecker.ProvideEvUpdate(zapLogger, configConfig, evBackDao)
	if err != nil {
		return nil, err
	}
	managerUserController := api.NewManagerUserController(baseController, zapLogger, configConfig, gorm, jwt, gmUserService, webEngine, evUpdate, pluginManager)
	esService := es_service.NewEsService(gorm)
	esController := api.NewEsController(baseController, zapLogger, esClientService, esService, jwt, configConfig)
	bigMode := big_mode_service.NewBigMode(zapLogger, configConfig)
	aiController := api.NewAiController(baseController, zapLogger, bigMode)
	indexController := api.NewIndexController(configConfig, zapLogger)
	service := process.ProvideService(zapLogger)
	pluginStoreService := pluginstore.NewPluginStoreService(pluginManager, configConfig, service, zapLogger, gorm)
	pluginsService, err := updatechecker.ProvidePluginsService(zapLogger, configConfig, evBackDao, pluginManager)
	if err != nil {
		return nil, err
	}
	pluginService := plugin_service.NewPluginService(gorm, pluginManager, zapLogger, service, configConfig, rbac, gmUserDao, jwt, evBackDao, pluginStoreService, pluginsService, gmOperaterLogService)
	evEService := eve_service.NewEvEService(zapLogger, evBackDao, configConfig, pluginManager, pluginsService)
	pluginInstaller := plugin_install_service.ProvideInstaller(configConfig, zapLogger, pluginManager, evBackDao, pluginStoreService, pluginsService)
	pluginController := api.NewPluginController(baseController, zapLogger, gorm, pluginService, evEService, pluginInstaller, gmUserService, jwt)
	live := live_svr.NewLive(zapLogger, configConfig, jwt, pluginManager)
	wsController := api.NewWsController(live, zapLogger)
	webServer := web.NewWebServer(webEngine, zapLogger, configConfig, rbac, middleWareService, gmOperaterController, managerRoleController, esLinkController, managerUserController, esController, aiController, indexController, pluginController, wsController)
	pluginUtilController := api.NewPluginUtilController(baseController, pluginService, esClientService, esService, zapLogger, configConfig, gmUserService, live, evEApi)
	pluginRpcServer := plugin_rpc.NewPluginRpcServer(zapLogger, configConfig, middleWareService, pluginUtilController)
	webView, err := webview.ProvideWebView(zapLogger, configConfig)
	if err != nil {
		return nil, err
	}
	backgroundServiceRegistry := backgroundsvcs.ProvideBackgroundServiceRegistry(webServer, evUpdate, pluginsService, pluginStoreService, pluginRpcServer, evEService, gmOperaterLogService, webView)
	server := NewServer(configConfig, migratorMigrator, zapLogger, gorm, backgroundServiceRegistry, esLinkService, evEService, gmUserService, pluginInstaller)
	return server, nil
}

func InitializeOrm(args *config.CommandLineArgs) (*orm.Gorm, error) {
	configConfig, err := config.InitConfig(args)
	if err != nil {
		return nil, err
	}
	zapLogger, err := logger.InitLog(configConfig)
	if err != nil {
		return nil, err
	}
	gorm, err := orm.NewGorm(configConfig, zapLogger)
	if err != nil {
		return nil, err
	}
	return gorm, nil
}

func InitializeEvApiDao(args *config.CommandLineArgs) (*dao.EvBackDao, error) {
	configConfig, err := config.InitConfig(args)
	if err != nil {
		return nil, err
	}
	zapLogger, err := logger.InitLog(configConfig)
	if err != nil {
		return nil, err
	}
	evEApi := eve_api.NewEvApi(configConfig, zapLogger)
	evBackDao := dao.NewEvBackDao(zapLogger, evEApi)
	return evBackDao, nil
}

func InitializeGmRoleEslinkCfgV2Dao(args *config.CommandLineArgs) (*dao.GmRoleEslinkCfgV2Dao, error) {
	configConfig, err := config.InitConfig(args)
	if err != nil {
		return nil, err
	}
	zapLogger, err := logger.InitLog(configConfig)
	if err != nil {
		return nil, err
	}
	gorm, err := orm.NewGorm(configConfig, zapLogger)
	if err != nil {
		return nil, err
	}
	gmRoleEslinkCfgV2Dao := dao.NewGmRoleEslinkCfgV2Dao(gorm)
	return gmRoleEslinkCfgV2Dao, nil
}

func InitializeProvideInstaller(args *config.CommandLineArgs) (*plugin_install_service.PluginInstaller, error) {
	configConfig, err := config.InitConfig(args)
	if err != nil {
		return nil, err
	}
	zapLogger, err := logger.InitLog(configConfig)
	if err != nil {
		return nil, err
	}
	pluginManager := manager.NewPluginManager()
	evEApi := eve_api.NewEvApi(configConfig, zapLogger)
	evBackDao := dao.NewEvBackDao(zapLogger, evEApi)
	service := process.ProvideService(zapLogger)
	gorm, err := orm.NewGorm(configConfig, zapLogger)
	if err != nil {
		return nil, err
	}
	pluginStoreService := pluginstore.NewPluginStoreService(pluginManager, configConfig, service, zapLogger, gorm)
	pluginsService, err := updatechecker.ProvidePluginsService(zapLogger, configConfig, evBackDao, pluginManager)
	if err != nil {
		return nil, err
	}
	pluginInstaller := plugin_install_service.ProvideInstaller(configConfig, zapLogger, pluginManager, evBackDao, pluginStoreService, pluginsService)
	return pluginInstaller, nil
}

// wire.go:

var wireSet = wire.NewSet(wire.Bind(new(registry.BackgroundServiceRegistry), new(*backgroundsvcs.BackgroundServiceRegistry)), live_svr.NewLive, api.NewWsController, webview.ProvideWebView, oauth.ProvideOAuthServiceRegistry, oauth.NewWorkWechat, big_mode_service.NewBigMode, api.NewAiController, plugin_install_service.ProvideInstaller, wire.Bind(new(manager.Service), new(*manager.PluginManager)), api.NewPluginController, process.ProvideService, migrator.NewMigrator, config.InitConfig, manager.NewPluginManager, pluginstore.NewPluginStoreService, eve_api.NewEvApi, eve_service.NewEvEService, dao.NewEvBackDao, logger.InitLog, dao.NewEslinkCfgV2Dao, dao.NewGmRoleDao, dao.NewGmUserDao, dao.NewEsLinkV2Dao, dao.NewGmRoleEslinkCfgV2Dao, dao.NewEslinkRoleCfgReletion, updatechecker.ProvidePluginsService, orm.NewGorm, cache_service.NewEsCache, request.NewRequest, response.NewResponse, api.NewBaseController, api.NewIndexController, updatechecker.ProvideEvUpdate, api.NewPluginUtilController, plugin_service.NewPluginService, api.NewEsController, api.NewEsLinkController, es.NewEsClientService, es_link_service.NewEsLinkService, es_service.NewEsService, api.NewGmOperaterController, gm_operater_log.NewGmOperaterLogService, api.NewManagerRoleController, gm_role.NewGmRoleService, api.NewManagerUserController, gm_user.NewGmUserService, jwt_svr.NewJwt, middleware.NewMiddleWareService, backgroundsvcs.ProvideBackgroundServiceRegistry, access_control.NewRbac, web_engine.NewWebEngine, web.NewWebServer, plugin_rpc.NewPluginRpcServer, NewServer)
