ai:
    bigmodekey: ""
checkforevupdates: true
checkforpluginupdates: true
dbtype: mysql
debug: true
espwdsecret: concat_mail!!->1340691923@qq.com
evkey: admin-xwl
log:
    logdir: logs
    storagedays: 4
mysql:
    dbname: test
    ip: 127.0.0.1
    port: "3306"
    pwd: 123456
    username: root
oauth:
    workwechat:
        agentid: ""
        corpid: ""
        enable: false
        secert: ""
plugin:
    loadpath: plugins
    storepath: plugins_store
pluginrpcport: 8091
port: 8090
rooturl: ""
sqlite:
    dbname: es_view.db
storefiledir: store_file_dir
translation:
    cfgdir: config/i18n
    lang: zh-cn
version: 0.0.15
watermarkcontent: ElasticView
